[package]
name = "http-client"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-stream = "0.3.6"
futures = "0.3"
http = "1"
pin-project-lite = "0.2"
serde = "1"
serde_json = "1"
tracing = "0.1"

[workspace]
resolver = "2"
members = ["crates/reqwest"]
