[package]
name = "http-client-reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "*"
http-client = { path = "../.." }
reqwest = { version = "0.12.8", features = ["stream"] }
futures = "0.3.30"
